services:
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:cached
      # - /app/node_modules   
    environment:
      VITE_API_URL: http://localhost:8000

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    image: node:apline 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 8000:8000
    environment: 
      DB_URL: 'mongodb+srv://fionagspencer:q7DFWxouFn2SfdNn@cluster0.9vzixga.mongodb.net/users'

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
     - dbdata:/data/db

volumes:
  dbdata: